-- 코드를 입력하세요
SELECT MEMBER_ID,MEMBER_NAME,GENDER,TO_CHAR(DATE_OF_BIRTH,'YYYY-MM-dd') as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE EXTRACT(MONTH FROM DATE_OF_BIRTH) ='03' AND GENDER = 'W' AND TLNO IS NOT NULL ORDER BY 1;